version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend_tedi:
    build:
      context: ./ergasia-front/
      dockerfile: Dockerfile
    container_name: frontend_tedi
    ports: 
    - 443:3000
    volumes: 
      - ./ergasia-front/src:/app/src
      - ./ergasia-front/public/assets:/app/public/assets
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build:
      context: ./ergasia-api/
      dockerfile: Dockerfile
    volumes:
      - "./ergasia-api/:/app"
    expose:
      - 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  db: